services:
  - type: web
    name: react-portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - source: "/static/**"
        headers:
          - key: "Cache-Control"
            value: "public, max-age=31536000, immutable"
      - source: "/**"
        headers:
          - key: "X-Frame-Options"
            value: "DENY"
          - key: "X-Content-Type-Options"
            value: "nosniff"
